# -*- coding: utf-8 -*-
"""load_monthly_forecast

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p_eH32rc-HhWM9Ko5ei3GZtfoT1gRmJN
"""

import pandas as pd
import boto3
from sqlalchemy import create_engine

# -------------------
# CONFIG
# -------------------
S3_BUCKET = "capstone-data-pace"
S3_KEY = "forecast_output/monthly_forecasts.csv"

DB_HOST = "tourism-forecast-db.cpmamie46yeu.us-east-2.rds.amazonaws.com"
DB_PORT = 5432
DB_NAME = "tourism_forecast"
DB_USER = "postgres"
DB_PASSWORD = "KPK01feb2002"

TABLE_NAME = "monthly_forecast"

# -------------------
# READ CSV FROM S3
# -------------------
s3 = boto3.client("s3")
obj = s3.get_object(Bucket=S3_BUCKET, Key=S3_KEY)
df = pd.read_csv(obj["Body"])

print("CSV loaded")
print(df.head())

# -------------------
# LOAD INTO RDS
# -------------------
engine = create_engine(
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

df.to_sql(
    TABLE_NAME,
    engine,
    if_exists="replace",   # table already exists
    index=False
)

print("✅ Data successfully loaded into RDS")